name: end_to_end

on:
  pull_request:
    branches:
      - main

jobs:
  end_to_end:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: read
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/alercebroker/ingestion_step
          VERSION=dev
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_IMAGE_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}

      - name: Ping to run end to end test in another repo
        run: |
          curl -X POST https://api.github.com/repos/alercebroker/pipeline-integration-test/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ingestion_step dev", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
